---
- name: Configure Apnea API Server
  hosts: all
  become: yes # Run tasks as root (sudo)
  vars:
    aws_region: "eu-central-1" 
    ecr_registry: "{{ ecr_registry_url }}"
    ecr_image: "{{ ecr_image_url }}"

  tasks:
    # --------------------
    # 1. OS Hardening & Prep
    # --------------------
    - name: Update apt cache and upgrade packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist

    - name: Install required dependencies
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - awscli
        state: present

    # --------------------
    # 2. Install Docker & Docker Compose
    # --------------------
    - name: Add Docker GPG apt Key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu jammy stable
        state: present

    # Notice we added docker-compose-plugin here!
    - name: Install Docker Engine and Compose
      ansible.builtin.apt:
        name: 
          - docker-ce
          - docker-compose-plugin
        state: present

    - name: Ensure Docker service is running
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    # --------------------
    # 3. Deploy the Multi-Container Stack
    # --------------------
    - name: Create project directory on server
      ansible.builtin.file:
        path: /opt/apnea
        state: directory
        mode: '0755'

    - name: Copy Prometheus configuration
      ansible.builtin.copy:
        src: prometheus.yml
        dest: /opt/apnea/prometheus.yml

    - name: Template docker-compose.yml to server
      ansible.builtin.template:
        src: docker-compose.yml.j2
        dest: /opt/apnea/docker-compose.yml

    - name: Log into AWS ECR
      ansible.builtin.shell: "aws ecr get-login-password --region {{ aws_region }} | docker login --username AWS --password-stdin {{ ecr_registry }}"
      changed_when: false 

    - name: Start Docker Compose Stack
      ansible.builtin.shell: docker compose up -d
      args:
        chdir: /opt/apnea